// <auto-generated />
using System;
using Importer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Importer.Migrations
{
    [DbContext(typeof(ImporterDbContext))]
    partial class ImporterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Importer.ImbalancePrice", b =>
                {
                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Area")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ImbalancePriceDKK")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ImbalancePriceEUR")
                        .HasColumnType("TEXT");

                    b.HasKey("TimestampUtc", "Area");

                    b.ToTable("ImbalancedPrices");
                });
#pragma warning restore 612, 618
        }
    }
}
